version: '3'
services:
  motion_detector:
    image: anfri/motion_detector
    environment:
      FRAME_COUNT: 50
      BIND_ADDRESS: 'motion_detector'
      COMMUNICATION_PORT: 60000
    devices:
      - '/dev/video0'
  video_browser:
    image: anfri/video_browser
    ports:
      - '8080:8080'
    environment:
      SERVER_ADDRESS: 'motion_detector'
      SERVER_PORT: 60000
      FLASK_ADDRESS: '0.0.0.0'
      FLASK_PORT: 8080
